### ISSUE TITLE
adding caption

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#2]
I would like to suggest to add (part of) the caption into the results under the specific thumbnail.

![image](https://user-images.githubusercontent.com/4609956/33067344-238477c0-ceae-11e7-8de0-30c934c362bc.png)

**Comment by myrmoteras** [comment]
captions don't need to be complete, but may be 50 letters or another operational number

**Comment by punkish** [comment]
the Zenodo API returns a description and a title. It is not clear which one should be used in the caption. Also, both of them are rather long text strings. Showing the first 50 or so characters also won't solve the issue because they first 50 or so characters are usually just meaningless text such as "Figures 1-4 of blah blah". One solution is to show the captions on the large versions of the images, but for that, I have to first implement a way to show the large version of an image when the thumbnail is clicked.

**Comment by punkish** [comment]
Since captions have now been in place for a while, I am closing this issue.
