### ISSUE TITLE
very slow results > 1min  for https://ocellus.info/?source=all&q=phylogeny+AND+plant

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#29]
I am trying to get all figures for phylogenies for the plants.

How can I get this? I am trying to run the query above, and get some, but mostly other taxa.

this query, if it would use the metadata keywords, then should provide the right answer, but probably not all because plantae might not be included in the keywords. 
https://ocellus.info/?source=all&q=phylogeny+AND+plantae

but I do not get a reply.

**Comment by punkish** [comment]
try the following https://ocellus.info/?source=all&q=phylogeny&kingdom=plantae&page=1&size=30

**Comment by punkish** [comment]
I am going to fix this. I think there is a way to do AND and OR searches, but I have to read up on it and implement it. Soon as it is working, I will let you know

**Comment by myrmoteras** [comment]
yes, this is fast now. But searching only for phylogeny is considerably slower

**Comment by punkish** [comment]
this is due to something weird with Contabo's delivery, that is all I can surmise. I tried just now, and you were correct -- it took 25s for me to get the result. Then I tried again (of course, refreshing the cache), and next time it took 266ms (one quarter of a second as opposed to 25seconds the first time). I tried the same query directly against the db on Contabo, and it worked very fast. But, logging on to Contabo seemed glacially slow. I having been noticing a lot of time lag with working on Contabo. I will continue to monitor and see if their system is the culprit or what. For now, Zenodeo (which powers Ocellus) is consistently very fast for just about everything I am testing on it. 

Please continue to let me know your observations
