### ISSUE TITLE
search results misleading

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#40]
in case, searching for `phylogeny`, the result is misleading, since the expectation is to get images with phylogenies. All th rest is not relevant
![image](https://github.com/punkish/ocellus/assets/4609956/12e9e643-4482-4ba4-b4d8-2731ff1b595f)

This is, because you search for the treatment full text, not the caption that is relevant. Possible to add this alternative?

Similary, this is also the case when searching for a taxon, and then get many other things are not the taxon searched.

For example, in our use case to search for phylogenies, it would be helpful to be able to get only trees which then would allow to analyse and compare them. This is what we need to do right now for a project with GBIF.

**Comment by punkish** [comment]
Donat,

In order to make the backend search flexible, this is how it works --

if you search for just `phylogeny`, the search is performed against the fulltext of the treatment. So, images from all treatments with the word `phylogeny` anywhere are returned, about ~7500 of them. But if you search for `captionText=phylogeny`, then the search is performed *only* against the image caption, and you get back about ~700 images. This way, one can do searches against both the treatment text as well as the images text.

Hope this helps.

![image](https://github.com/punkish/ocellus/assets/349242/98eba042-3eb6-4659-ab85-d1fe8534731b)

**Comment by punkish** [comment]
added more examples

![image](https://github.com/punkish/ocellus/assets/349242/b11e9906-83ae-4e2a-ac13-c46ec190b0c8)
